import Card from '@components/card';
import Footer from '@components/footer';
import Header from '@components/header';
import Whatsapp from '@components/whatsapp';
import '@styles/global.css';

export const metadata = {
  title: 'Our products',
  description: 'Generated by create next app',
};

const cardsData = [
  {
    imageUrl: '/1.jpg',
    title: 'Product 1',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: '19.99',
  },
  {
    imageUrl: '/2.jpg',
    title: 'Product 2',
    description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: '29.99',
  },
  {
    imageUrl: '/3.jpg',
    title: 'Product 3',
    description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
    price: '39.99',
  },
  {
    imageUrl: '/1.jpg',
    title: 'Product 1',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    price: '19.99',
  },
  {
    imageUrl: '/2.jpg',
    title: 'Product 2',
    description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: '29.99',
  },
  {
    imageUrl: '/3.jpg',
    title: 'Product 3',
    description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
    price: '39.99',
  },
];

const Layout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <main>
          <Header />
          <div className="px-14 mt-28">{children}</div>
          <Whatsapp />

          <div className="flex flex-wrap justify-center items-start p-8">
      {cardsData.map((card, index) => (
        <div key={index} className="w-full sm:w-1/2 md:w-1/3 lg:w-1/3 xl:w-1/3 p-4">
          <Card {...card} />
        </div>
      ))}
    </div>

          <Footer />

        </main>
      </body>
    </html>
  );
};

export default Layout;
